apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: default
data:
  key: QVFESVRidGREWVJZSnhBQVg0K1NzRTd5RDFOZFVjWGptY05NMWc9PQ==   # Replace with your admin key
type: kubernetes.io/rbd

